changelog:
  categories:            # リリースノートのカテゴリ設定
    - title: Enhancement # リリースノートへ「Enhancement」というカテゴリを作成する
      labels:
        - enhancement    # 「Enhancement」へ掲載するプルリクエストのラベルを指定する
    - title: Bug Fixes a
      labels:            # プルリクエストのラベルは複数定義できる
        - bug
        - fixes
