name: Job summaries
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: job summary
        run: | # マークダウンテキストをジョブサマリーへ出力
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"
