name: Run name
run-name: Run by @${{ github.actor }} # ワークフロー実行名の指定
on: push
jobs:
  print:
    name: Super Useful Job
    runs-on: ubuntu-latest
    steps:
      - name: Amazing Script
        run: echo "Hello"
